version: '3'
services:
  scada:
    build: .
    ports:
      - "1881:1881"
    networks:
      - isolated_scada_net
    cap_add:
      - NET_ADMIN

networks:
  isolated_scada_net:
    driver: bridge
