name: oilsprings

networks:
  l2_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24

  l3_scada_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24

  l3_security_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.4.0/24

  l3_pentest_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24

services:
  plc:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\plc
    container_name: oilsprings_plc
    cap_add:
      - NET_ADMIN
    networks:
      l2_network:
        ipv4_address: 10.10.2.10
    ports:
      - "8080:8080"
    restart: unless-stopped

  scada:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\scada
    container_name: oilsprings_scada
    cap_add:
      - NET_ADMIN
    networks:
      l3_scada_network:
        ipv4_address: 10.10.3.20
    ports:
      - '8081:1881'
    restart: unless-stopped
    dns:
      - 127.0.0.11

  ews:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\ews
    container_name: oilsprings_ews
    cap_add:
      - NET_ADMIN
    networks:
      l3_scada_network:
        ipv4_address: 10.10.3.11
    ports:
      - "8083:5911"
    restart: unless-stopped

  ids:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\ids
    container_name: oilsprings_ids
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    networks:
      l3_security_network:
        ipv4_address: 10.10.4.41
    ports:
      - "8084:1443"
    restart: unless-stopped

  collector:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\collector
    container_name: oilsprings_collector
    cap_add:
      - NET_ADMIN
    networks:
      l3_security_network:
        ipv4_address: 10.10.4.40
    ports:
      - "8085:2443"
    restart: unless-stopped

  pentest:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\pentest
    container_name: oilsprings_pentest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      l3_pentest_network:
        ipv4_address: 10.10.5.50
    ports:
      - "2222:22"
      - "8086:3443"
    restart: unless-stopped

  router:
    build: C:\Users\navin\OneDrive\문서\MY cyber\CyberPro\labshock\oilsprings\router
    container_name: oilsprings_router
    cap_add:
      - NET_ADMIN
    networks:
      l2_network:
        ipv4_address: 10.10.2.2
      l3_scada_network:
        ipv4_address: 10.10.3.2
      l3_security_network:
        ipv4_address: 10.10.4.2
      l3_pentest_network:
        ipv4_address: 10.10.5.2
    ports:
      - "8087:5443"
    restart: unless-stopped
